In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Nassau Candy Distributor.csv to Nassau Candy Distributor (1).csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("Nassau Candy Distributor.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [ ]:
df.shape

(10194, 18)

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')

In [ ]:
df.describe()

,Row ID,Ship Date,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2028-10-23 23:20:43.790465024,134468.961154,13.908537,3.791838,9.166451,4.742087
min,1.000000,2026-06-30 00:00:00,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,2027-11-09 00:00:00,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,2028-12-18 00:00:00,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,2029-11-08 00:00:00,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,2030-06-28 00:00:00,192314.000000,260.000000,14.000000,130.000000,130.000000
std,2942.898656,NaN,20231.483007,11.341020,2.228317,6.643740,5.061647

In [ ]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    dayfirst=True
)
print(df["Order Date"].dtype)

datetime64[ns]

In [ ]:
df['Ship Date'] = pd.to_datetime(
    df['Ship Date'],
    dayfirst= True
)
print(df['Ship Date'].dtype)

datetime64[ns]

In [ ]:
df['Lead_Time'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

print(df['Lead_Time'].describe())

NameError: name 'df' is not defined

In [ ]:
df['Lead_Time'].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead_Time, dtype: float64

In [ ]:
df.sort_values(
    'Lead_Time',
    ascending=False
)[['Order Date','Ship Date','Lead_Time']].head(20)

      Order Date  Ship Date  Lead_Time
10183 2025-12-29 2030-06-28       1642
10175 2025-12-29 2030-06-28       1642
7167  2025-03-13 2029-09-10       1642
9540  2025-11-19 2030-05-19       1642
10165 2025-12-28 2030-06-27       1642
10164 2025-12-28 2030-06-27       1642
10160 2025-12-28 2030-06-27       1642
8087  2025-07-08 2030-01-05       1642
10120 2025-12-24 2030-06-23       1642
10111 2025-12-24 2030-06-23       1642
10141 2025-12-25 2030-06-24       1642
8083  2025-07-08 2030-01-05       1642
8080  2025-07-08 2030-01-05       1642
8071  2025-07-08 2030-01-05       1642
8059  2025-07-06 2030-01-03       1642
8058  2025-07-06 2030-01-03       1642
8032  2025-07-03 2029-12-31       1642
8030  2025-07-03 2029-12-31       1642
8027  2025-07-01 2029-12-29       1642
8026  2025-07-01 2029-12-29       1642

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
 18  Lead_Time       10194 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(4), object(10)
memory usage: 1.5+ MB

In [ ]:
df['Lead_Time'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

In [ ]:
df[['Order Date','Ship Date','Lead_Time']].sample(10)

     Order Date  Ship Date  Lead_Time
7306 2025-03-28 2029-09-21       1638
5737 2025-09-17 2029-03-12       1272
608  2024-06-09 2026-12-07        911
3948 2024-12-08 2028-06-02       1272
2686 2024-06-13 2027-12-10       1275
7782 2025-06-01 2029-11-24       1637
740  2024-07-12 2027-01-06        908
4446 2025-03-13 2028-09-04       1271
4744 2025-05-07 2028-10-31       1273
8346 2025-08-17 2030-02-14       1642

In [ ]:
df['Lead_Time'].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead_Time, dtype: float64

In [ ]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df['Lead_Time'] = (df['Ship Date'] - df['Order Date']).dt.days

print(df['Lead_Time'].head(20))

0     909
1     909
2     909
3     909
4     912
5     909
6     909
7     906
8     909
9     909
10    909
11    907
12    909
13    909
14    910
15    910
16    909
17    909
18    910
19    910
Name: Lead_Time, dtype: int64

In [ ]:
df[['Order Date','Ship Date','Lead_Time']].head()

  Order Date  Ship Date  Lead_Time
0 2024-01-03 2026-06-30        909
1 2024-01-04 2026-07-01        909
2 2024-01-04 2026-07-01        909
3 2024-01-04 2026-07-01        909
4 2024-01-05 2026-07-05        912

In [ ]:
total_sales = df['Sales'].sum()
total_profit = df['Gross Profit'].sum()
total_units = df['Units'].sum()
avg_lead_time = df['Lead_Time'].mean()
profit_margin= (total_profit/total_sales)*100

In [ ]:
print("Total_Sales",total_sales)
print("Gross_Profit",total_profit)
print("Total_Units",total_units)
print("Avg_Lead_Time",avg_lead_time)
print("Profit_Margin",profit_margin)

Total_Sales 141783.63
Gross_Profit 93442.8
Total_Units 38654
Avg_Lead_Time 1320.8418677653522
Profit_Margin 65.90521063679918

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv("Nassau_Candy_cleaned.csv", index = False)